branch-defaults:
  master:
    environment: sjc-hlf-dataentry
environment-defaults:
  sjcarchiveadmin:
    branch: null
    repository: null
global:
  application_name: SJC_Archive
  default_ec2_keyname: sjc_archive_eb
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/PHP 7.1 running on
    64bit Amazon Linux/2.7.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
